### ISSUE TITLE
Reset Funktion

### ISSUE THREAD

**Issue by robinczarnetzki** [sarcaustech/meeting-moderation-cards#1]
[Feature Request]
Als Nutzer (ggf. in einer expliziten Admin Rolle) möchte ich über einen Reste-Button alle aktiven Karten aller Nutzer deaktivieren, um somit auch Karten von Nutzern zu entfernen, die während eines Meetings eingeschlafen sind oder auch nach einer Abstimmung, wenn viele Karten aktiviert wurden.

**Comment by sarcaustech** [comment]
Global reset implemented. See 5a4b44093f80f02c6e59335a1a6d3958ad297d66
